# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 22:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=128)),
                ('distance', models.IntegerField(help_text=b'meters')),
                ('duration', models.IntegerField(help_text=b'seconds')),
                ('start_address', models.CharField(max_length=128)),
                ('start_location', models.CharField(max_length=128)),
                ('end_address', models.CharField(max_length=128)),
                ('end_location', models.CharField(max_length=128)),
                ('bounds', models.CharField(max_length=128)),
                ('steps', models.TextField(blank=True, help_text=b'JSON steps', null=True)),
                ('fastest', models.BooleanField(db_index=True, help_text=b'Used to mark the fastest result.')),
                ('monitor_results', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.MonitorResults')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avoidance', models.CharField(blank=True, max_length=64, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('latest_result', models.IntegerField(blank=True, help_text=b'How long until destination; In seconds.', null=True)),
                ('latest_result_summary', models.CharField(max_length=128)),
                ('latest_result_at', models.DateTimeField(blank=True, null=True)),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_location', to='places.Place')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_location', to='places.Place')),
            ],
        ),
        migrations.AddField(
            model_name='monitorresults',
            name='place_monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.PlaceMonitor'),
        ),
    ]
