# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placemonitor',
            name='alert_threshold',
            field=models.IntegerField(blank=True, help_text=b'seconds', null=True),
        ),
        migrations.AlterField(
            model_name='placemonitor',
            name='latest_result_summary',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
