# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20160404_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_string', models.CharField(max_length=256)),
                ('place_monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.PlaceMonitor')),
            ],
        ),
    ]
