# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_monitorfrequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='placemonitor',
            name='phone_number',
            field=models.IntegerField(default=b'5125224361'),
        ),
    ]
