# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zwave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_classes', models.CommaSeparatedIntegerField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        migrations.AddField(
            model_name='instance',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zwave.Device'),
        ),
    ]
