# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwave', '0003_auto_20151221_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='value',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
