# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwave', '0005_auto_20151226_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandclass',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
